### ISSUE TITLE
Proper escaping for strings

### ISSUE THREAD

**Issue by krzkaczor** [bahmutov/snap-shot-core#117]
If snapshotted text has characters like ` or `${` it will result in an error. They should be escaped before save.

**Comment by azu** [comment]
I've met same error.

Example:

```js
snapShot({
    what: "This is `code`.",
    file: __filename,
    specName: "test",
    ext: ".snap"
})
```

Currently, `snap-shot-core`'s file-system save it as following format.

    exports['test'] = `
      This is `code`.
    `

`saveSnapshots` will succeed but `loadSnapshots` will fail.
Because, following snapshot file is not valid syntax as Node.js code.

## Actual

    exports['test'] = `
      This is `code`.
    `

## Expected

    exports['test'] = `
      This is \`code\`.
    `


https://github.com/bahmutov/snap-shot-core/blob/2e11f5e266af97bac3c9d59623c1a43bda5cda2d/src/file-system.js#L86-L100

https://github.com/bahmutov/snap-shot-core/blob/2e11f5e266af97bac3c9d59623c1a43bda5cda2d/src/file-system.js#L58-L70
